# Generated by Django 2.1.4 on 2019-01-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_auto_20190128_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='URL старницы')),
                ('text', models.TextField(verbose_name='Текст с ошибкой')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сообщение об ошибке',
                'verbose_name_plural': 'Сообщения об ошибках',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(choices=[('news', 'Поделиться хорошей новостью'), ('event', 'Поделиться событием'), ('history', 'Поделиться своей историей'), ('person', 'Предложить героя'), ('question', 'Задать вопрос')], max_length=255, verbose_name='Тема обращения'),
        ),
    ]
